---
title: "branch"
output: html_document
---


```{r}
a<-read.lp("b_a.lp")
a
```

```{r}
solve(a)
get.objective(a)
get.constraints(a)

get.variables(a)
```
Here Branch 1 = 3 
z value is 41.25

1. we are doing for 3<=x1
```{r}
b<-read.lp('b_b.lp')
b
```

BRANCH 1 !!!


```{r}
solve(b)
get.objective(b)
get.constraints(b)

get.variables(b)
```
z value is 39
and both x1 and x2 = 3 and BEST Solution 
```{r}
c<-read.lp('b_c.lp')
c
solve(c)
get.objective(c)
get.constraints(c)

get.variables(c )
```
 
 Above z value is 41 and x1 = 4 x2 = 1.8
 
```{r}
c1<-read.lp('c_c1.lp')
c1
solve(c1)
get.objective(c1)
get.constraints(c1)

get.variables(c1)
```
 
```{r}
c2<-read.lp('c_c2.lp')
c2
solve(c2)
get.objective(c2)
get.constraints(c2)

get.variables(c2)
```
 In fesable solution
 
```{r}
c1_1<-read.lp('c_c1_1.lp')
c1_1
solve(c1_1)
get.objective(c1_1)
get.constraints(c1_1)

get.variables(c1_1)
```

 Best Solution So far x1 = 5, x2 = 0 z = 40
 
 
```{r}
c1_2<-read.lp('c_c1_2.lp')
c1_2
solve(c1_2)
get.objective(c1_2)
get.constraints(c1_2)
get.variables(c1_2)


```
 // In Feseable//
 
 BRANCH 2 !!
 
```{r}
b2<-read.lp('b2.lp')
b2
solve(b2)
get.objective(b2)
get.constraints(b2)

get.variables(b2)
```
  Here 
 3<=  x1 >=4 is already been done  for first branch so we wont be doing it again 
 
```{r}
b2_1<-read.lp('b2_1.lp')
b2_1
solve(b2_1)
get.objective(b2_1)
get.constraints(b2_1)

get.variables(b2_1)

```
 
 So from the best solution it is clear that x1 =5 and x2 = 0 has the best solution !!